project:
  type: website
  output-dir: docs
  
  preview: 
    browser: true
    watch-inputs: true
    navigate: true

  render:
    - "*.qmd"
    - "*.md"
    - "!etc/"

  resources:
  - "files/**"
  - "etc/**"

website:
  title: "Grupo de Trabajo de Datos Funcionales de la SEIO"
  image: images/fda-logo-150px.png
  favicon: images/fda-favicon.png
  open-graph: true
  site-url: https://fdaseio.github.io/
  repo-url: https://github.com/fdaseio/fdaseio.github.io
  navbar:
    background: "#f0eeeb"
    logo: images/fda-logo-150px.png
    logo-alt: "Grupo de Trabajo de Datos Funcionales de la SEIO"
    title: false
    collapse-below: lg
    right:
      - text: "Sobre el grupo"
        menu: 
        - text: "Quiénes somos"
          href: about-rwds.qmd
        - text: "Cómo unirse"
          href: join.qmd
        - text: "Contacto"
          href: contact.qmd
      - text: "Eventos" 
        href: eventos/index.qmd
      - text: "Miembros"
        href: miembros/index.qmd

  page-navigation: true

  page-footer:
    background: "#000000"
    left: |
      Copyright &copy; 2025 FDA-SEIO
    center:  
      - href: https://github.com/fdaseio/fdaseio.github.io
        icon: github
      - href: https://www.researchgate.net/lab/FDA-working-group-Spanish-Society-of-Stat-and-OR-SEIO-Paula-Navarro-Esteban
        text:  "{{< iconify fa6-brands researchgate >}}"
    right: |
      [Terminos & Condiciones](/ts-and-cs.qmd)

format:
  html:
    theme: [lux, rwds.scss]
    css: rwds.css
    toc: true
    grid:
      sidebar-width: 0px
      body-width: 1000px
      margin-width: 250px

execute: 
  freeze: auto